<?php
if($this->returnMessage) {
	echo "<p class=\"error\">$this->returnMessage</p>";
	echo "<p class=\"error\"return message</p>";
}
?>
   	<div class="filter-tab">      
   	<form name="Search" method="Post" action="">
     <div class="fields"><input id="SerialNumber" name="SerialNumber" type="text" class="form-control"/></div> 
    <div><button class="searchbtn" value="Submit" type="submit" onClick="submit()">Search</button></div>
	</form>    
    </div>
    