<?php 
if($this->returnMessage) {
	echo "<p class=\"error\">$this->returnMessage</p>";
}
?>

<div class="filter-tab">      
	<div class="fields"><input type="text" class="form-control"/></div> 
	<div class="searchbtn">Search</div>
</div>
<div class="line-break2"></div> 
<div class="tablestlye">
	<table align="center">
    	<tr>
        	<td class="td-title">Serial Number</td>
            <td class="td-title">Last Merchant Location</td>
            <td class="td-title">Terminal Type</td>
            <td class="td-title">Status</td>
            <td class="td-title">Account Reference</td>
            <td class="td-title">Action</td>
        </tr>
        <tr>
        	<td>4654165165165106</td>
            <td>BP Midrand</td>
            <td>EFT960G</td>
            <td>QC Pending</td>
            <td>Account Reference</td>
            <td><a href="#"><div class="tblbtn">View</div></a></td>
        </tr>
    </table>    
</div>
<div class="line-break2"></div> 
<div class="action-bar"><a href="#"><div class="submitbtn clearfix">Submit</div></a></div>   
</div>   