<?php 
echo $this->returnMessage;
?>
<h1>Login</h1>
    <form name="login" method="post" action="login">
        <div class="label">Username:</div>
        <div class="fields"><input name="UserName" type="text" class="form-control"/></div>
        <div class="label">Password:</div>
        <div class="fields"><input name="Password" type="password" class="form-control"/></div>        
        <div class="button-panel"><button class="button" value="Submit" type="submit" onClick="submit()">Submit</button></div>
    </form>    