<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Login - Title</title>
<link href="<?=$this->baseUrl()?>/styles/login.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <div id="logo"><img src="<?=$this->baseUrl()?>/images/logo.jpg" width="194" height="76" /></div>
    <div class="heading-text">Title</div>
    <div class="login-container">
  			<!--CONTENT -->
		    <?= $this->layout()->content ?>       
	</div>
<div class="footer">&copy; 2017 Uplink Technologies </div>
</div> 
</body>
</html>